/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMovie: typeof import('./src/components/Advice/movies/AddMovie.vue')['default']
    BookTab: typeof import('./src/components/Advice/BookTab.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModalAddMovie: typeof import('./src/components/Advice/movies/ModalAddMovie.vue')['default']
    MoviesList: typeof import('./src/components/Advice/movies/MoviesList.vue')['default']
    MovieTab: typeof import('./src/components/Advice/MovieTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMovieList: typeof import('./src/components/Advice/movies/SearchMovieList.vue')['default']
    SerieTab: typeof import('./src/components/Advice/SerieTab.vue')['default']
    TabItems: typeof import('./src/components/Advice/TabItems.vue')['default']
    TmdbTable: typeof import('./src/components/Advice/movies/TmdbTable.vue')['default']
  }
}
